

arte="""
█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
█        ____             _    _                        ____                                               _           _  █
█       / ___|  ___  ___ | |_ (_)  ___   _ __          |  _ \   ___    ___  _   _  _ __ ___    ___  _ __  | |_   __ _ | | █
█      | |  _  / _ \/ __|| __|| | / _ \ | '_ \         | | | | / _ \  / __|| | | || '_ ` _ \  / _ \| '_ \ | __| / _` || | █
█      | |_| ||  __/\__ \| |_ | || (_) || | | |        | |_| || (_) || (__ | |_| || | | | | ||  __/| | | || |_ | (_| || | █
█       \____| \___||___/ \__||_| \___/ |_| |_|        |____/  \___/  \___| \__,_||_| |_| |_| \___||_| |_| \__| \__,_||_| █
█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█
█                                            __ __   ___   __  _   _   _                                                  █
█                                           |  V  | | __| |  \| | | | | |                                                 █
█                                           | \_/ | | _|  | | ' | | \ / |                                                 █
█                                           |_| |_| |___| |_|\__|  \___/                                                  █
█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█
█                                                                                                                         █
█                                      __                                                                                 █
█ /|       /\   _   _  _  _   _   _   |  \  _   _      _   _  _  |_  _                                                    █
█  | .    /--\ (_) |  (- (_) (_| |    |__/ (_) (_ |_| ||| (- | ) |_ (_)                                                   █
█              _/        _/                                                                                               █
█ __                                                                                                                      █
█  _)      |\/|  _   _ |_  _  _   _   |_  _   _|  _   _   |  _   _    _|  _   _      _   _  _  |_  _   _                  █
█ /__ .    |  | (_) _) |_ |  (_| |    |_ (_) (_| (_) _)   | (_) _)   (_| (_) (_ |_| ||| (- | ) |_ (_) _)                  █
█                                                                                                                         █
█ __        __                      __                                                                                    █
█  _)      |__)      _  _  _   _   |  \  _   _      _   _  _  |_  _                                                       █
█ __) .    |__) |_| _) (_ (_| |    |__/ (_) (_ |_| ||| (- | ) |_ (_)                                                      █
█                                                                                                                         █
█           __                         __                                                                                 █
█ |__|      |_  | .  _  .  _   _   _   |  \  _   _      _   _  _  |_  _                                                   █
█    | .    |__ | | ||| | | ) (_| |    |__/ (_) (_ |_| ||| (- | ) |_ (_)                                                  █
█                                                                                                                         █
█  __       __                                                                                                            █
█ |_       (_   _  | .  _                                                                                                 █ 
█ __) .    __) (_| | | |                                                                                                  █
█                                                                                                                         █
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
"""

bye="""
█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
█                             _   _              _            _                               _                           █
█                            | | | |  __ _  ___ | |_   __ _  | | _   _   ___   __ _   ___    | |                          █
█                            | |_| | / _` |/ __|| __| / _` | | || | | | / _ \ / _` | / _ \   | |                          █
█                            |  _  || (_| |\__ \| |_ | (_| | | || |_| ||  __/| (_| || (_) |  |_|                          █
█                            |_| |_| \__,_||___/ \__| \__,_| |_| \__,_| \___| \__, | \___/   (_)                          █ 
█                                                                             |___/                                       █
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
"""

base_datos=[]


def desea():
    print(" ")
    opcion=input("¿Desea ingresar otro documento? (S/n):  ")
   
    if opcion=="S" or opcion=="s":
            print("══════════════════════════════════════════════════════ ")
            agregar_documento()
    elif opcion=="n" or opcion=="N":
         print(" ")
         volver=input("PULSE ENTER PARA VOLVER AL MENU ↲ ")
    else:
        print(" ")
        print("ERROR , INGRESE UN COMANDO VALIDO  ❌   ")
        print(" ")
        desea()
        


def agregar_documento():
    ID_documento = len(base_datos) +1
    print(" ")
    print("ID ➜ ", ID_documento)
    print(" ")
    Titulo=input("➤   INGRESE EL TITULO: ")
    print(" ")
    nombre=input("➤   INGRESE SU NOMBRE: ")
    print(" ")
    fecha=input("➤   INGRESE LA FECHA: ")
    print(" ")
    contenido=input("➤   INGRESE EL CONTENIDO: ")
    print(" ")
    firma=input("➤   INGRESE SU FIRMA: ")
    base_datosD={"ID": ID_documento,"Titulo:":Titulo,"Nombre:":nombre,"Fecha:":fecha,"Contenido:":contenido,"Firma:":firma}
    base_datos.append(base_datosD)
    print(" ")
    print("DOCUMENTO AGREGADO CON EXITO! ✅")
    desea()


def mostrar_documentos():
    if len(base_datos)==0:
        print(" ")
        print("NO HAY DOCUMENTOS REGISTRADOS ❌    ")
        print(" ")
    else:
        for doc in base_datos:
            print("ID:",doc["ID"])
            print(" ")
            print("            ",doc["Titulo:"])
            print(" ")
            print("Nombre: " + doc["Nombre:"] + "               " + "Fecha: " + doc["Fecha:"])
            print(" ")
            print("Contenido:",doc["Contenido:"])
            print(" ")
            print("          ","Firma:", doc["Firma:"])
            print(" ")
            print("═══════════════════════════════════════════════════")
            print(" ")
        print(" ")
    volver=input("PULSE ENTER PARA VOLVER AL MENU ↲ ")

def buscar_documento():
    if len(base_datos) == 0:
        print(" ")
        print("NO HAY DOCUMENTOS REGISTRADOS ⛔ ")
        print(" ")
        volver=input("PULSE ENTER PARA VOLVER AL MENU ↲ ")
    else:
        print(" ")
        id_buscado = int(input("INGRESE EL ID DEL DOCUMENTO QUE QUIERE BUSCAR ➜  "))
        encontrado=False
        for doc in base_datos:
            if doc["ID"] == id_buscado:
                encontrado=True
                print(" ")
                print("DOCUMENTO ENCONTRADO! 🔍 ✅")
                print(" ")
                print("═══════════════════════════════════════════════════")
                print("ID:", doc["ID"])
                print(" ")
                print("            ",doc["Titulo:"])
                print(" ")
                print("Nombre: " + doc["Nombre:"] + "               " + "Fecha: " + doc["Fecha:"])    #Para imprmir la fecha al lado del nombre
                print(" ")
                print( doc["Contenido:"])
                print(" ")
                print("          ","Firma:", doc["Firma:"])
                print(" ")
                print("═══════════════════════════════════════════════════")
                desea=input("¿Desea buscar otro documento? (s/n): ")
                if desea=="s" or desea=="S":
                    buscar_documento()
                else:
                    menu()
                break #para que no se imprima no encontrado cada vez
                
        if encontrado== False:
            print(" ")
            print("DOCUMENTO NO ENCONTRADO 🔍 ⛔")
            print(" ")
            desea=input("¿Desea buscar otro documento? (s/n): ")
            if desea=="s" or desea=="S":
                buscar_documento()
            else:
                menu()

def eliminar():
    if len(base_datos)==0:
        print(" ")
        print("NO HAY DOCUMENTOS PARA ELIMINAR! ⛔")
        print(" ")
        volver=input("PULSE ENTER PARA VOLVER AL MENU ↲ ")
    else:
     print(" ")
     id_eliminar = int(input("INGRESE EL ID DEL DOCUMENTO QUE DESEA ELIMINAR 🚮 : "))   
     print(" ")
    encontrado = False

    for doc in base_datos:
                if doc["ID"] == id_eliminar:
                    seguro=input("ESTA SEGURO DE ELIMINAR EL DOCUMENTO?(S/n)  ⚠️:  ")
                
                    if seguro=="S" or seguro=="s":
                        encontrado = True
                        base_datos.remove(doc)
                        print(" ")
                        print("DOCUMENTO ELIMINADO CON EXITO! 🗑️ ✅ ")
                        print(" ")
                        desea_eliminar=input("DESEA ELIMINAR OTRO DOCUMENTO (S/n): ")
                        if desea_eliminar=="s" or desea_eliminar=="S":
                            eliminar()
                    if seguro=="N" or seguro=="n":
                        print(" ")
                        print("NO SE ELIMINO NINGUN DOCUMENTO  🗑️   ❌    ")
                        print(" ")
                        volver=input("PULSE ENTER PARA VOLVER AL MENU ↲ ")   
                    else: 
                        print(" ")
                        print("OPCION INVALIDA, PULSE ENTER PARA VOLVER AL MENU ↲ ")
                        print(" ")      
    if encontrado == False:
            print(" ")
            print("DOCUMENTO NO ENCONTRADO 🔍 ⛔")
            print(" ")
            volver = input("PULSE ENTER PARA VOLVER AL MENU ↲ ")             
def menu():
    
    while True:
        
        print(arte)
        opcion = input("SELECCIONE UNA OPCION: ")

        if opcion == "1":
            agregar_documento()
        elif opcion == "2":
            mostrar_documentos()
        elif opcion=="3":
            buscar_documento()
        elif opcion=="4":
            eliminar()
        elif opcion == "5":
            segurosalir=input("ESTA SEGURO DE SALIR? (S/n)  ⚠️ : ")  #Si no se cierra al primer intento, intentelo de nuevo
            if segurosalir=="S" or segurosalir=="s":
                print(bye)
                return
            elif segurosalir=="N" or segurosalir=="n":
                print(" ")
                volver = input("PULSE ENTER PARA VOLVER AL MENU ↲ ") 
                print(" ")
            else:
                print(" ")
                volver= input("OPCION INVALIDA  ⛔ , PULSE ENTER PARA VOLVER AL MENU  ↲  ")        
                print(" ")
        else:
            print("Opción inválida. Intente nuevamente.")
    
menu()
